### ISSUE TITLE
Test outdated

### ISSUE THREAD

**Issue by jmmendivil** [gextech/jquery-velcro#5]
Also... Any clue why test aren't passing even when index values are true in manual-browser?

**Comment by pateketrueke** [comment]
I'm still stuck on that! I can't fix that this week, but I'll check more later. ;)

**Comment by jmmendivil** [comment]
I can update the specs but weird thing is: when I remove all scenarios from **main.feature** and run `./node_modules/.bin/nahual --standalone` it runs all the (removed) scenarios, could it be a nahual issue?

**Comment by pateketrueke** [comment]
Yup, `nahual` will generate some files for Nightwatch, just remove those generated sources and run the task again.

**Comment by jmmendivil** [comment]
Tests are working now...
Next task should be fix travis-cli job

**Comment by pateketrueke** [comment]
Sadly, I can't get the tests working on Travis... yet!

**Comment by pateketrueke** [comment]
Fixed now, but is not done yet.
